# Generated by Django 4.1.2 on 2022-10-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('date_of_birth', models.DateField(max_length=10, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=45, null=True)),
                ('address', models.CharField(max_length=20, null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10, null=True)),
                ('any_medications', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=10, null=True)),
                ('if_yes', models.TextField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10, null=True)),
            ],
        ),
    ]
