# Generated by Django 4.1.2 on 2022-10-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='any_medications',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='if_yes',
        ),
        migrations.AddField(
            model_name='patient',
            name='Taking_any_medications_currently',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='if_yes_please_list_below',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
