# Generated by Django 4.1.2 on 2022-10-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalSystem', '0002_remove_patient_any_medications_remove_patient_if_yes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=45, null=True)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('county', models.CharField(choices=[('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Nyeri', 'Nyeri'), ('Muranga', 'Muranga'), ('Kakamega', 'Kakamega'), ('Kirinyaga', 'Kirinyaga'), ('Kisumu', 'Kisumu')], max_length=20, null=True)),
                ('specialization', models.CharField(choices=[('Neurologist', 'Neurologist'), ('Dentist', 'Dentist'), ('ENT', 'ENT'), ('Oncologist', 'Oncologist'), ('Cardiologist', 'Cardiologist'), ('Eye Specialist', 'Eye Specialist'), ('Orthopedic', 'Orthopedic'), ('Gynecologist', 'Gynecologist'), ('Dermatologist', 'Dermatologist'), ('Opthamologists', 'Ophamologist'), ('Other', 'Other')], max_length=30, null=True)),
                ('work_type', models.CharField(choices=[('Fulltime', 'Fulltime'), ('Parttime', 'Partime'), ('Remote', 'Remote')], max_length=20, null=True)),
            ],
        ),
    ]
