# Generated by Django 4.1.2 on 2022-10-19 05:36

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalSystem', '0004_alter_doctor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
