# Generated by Django 4.1.2 on 2022-10-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalSystem', '0005_doctor_country_patient_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointmnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=45, null=True)),
                ('contact', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
