# Generated by Django 4.1.2 on 2022-10-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalSystem', '0007_alter_doctor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmnet',
            name='appointment_date',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appointmnet',
            name='contacting_method',
            field=models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointmnet',
            name='contacting_time',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Noon', 'Noon'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointmnet',
            name='first_time_visit',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointmnet',
            name='services_interested',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
